# Site settings
title: "Guoxin Wang"
description: "Nice to meet U."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Guoxin Wang"
resume_title:                   "Researcher | IEEE Senior Member"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "guoxin.wang@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Currently the head of the Intelligent Algorithms Department at JD Health, overseeing the AI core modeling team, search team and recommendation team, responsible for technological innovation and solution development in the field of medical AI.</p>
<p>I have published more than ten international papers in AAAI, IEEE TMM, SIGKDD, etc. My main research areas are search engine, large-scale language models and multimodal learning. I serve as the technical lead and main author of JingYiQianXun, which is the leading LLM in <a href='https://medbench.opencompass.org.cn/leaderboard'>MedBench.</a></p> 
<p>With over ten years of research experience in artificial intelligence, I possess rich practical experience at the forefront of innovative technology and have led multiple core technological breakthroughs across various fields, including health care, e-commerce, search engines, content recommendation.</p>
"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
#  resume_github_url:            "https://github.com/jglovier/resume-template"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #  resume_website_url:           "http://joelglovier.com"
  #  resume_medium_url:            "https://medium.com/@jglovier"
# resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
